graph TB
    Draft -- ADR Pull Request Written --> Proposed
    Proposed -- Emailed --> C{Consensus}
    C --> |Yes| Merged
    C --> |No| A{Concerns Addressed?}
    A --> |Yes| Merged
    A --> |No| Discussion
    Discussion --> O{Voting Outcome}
    O --> |Accepted| Merged
    O --> |Rejected| Merged
    Merged --> U[Update other Issues]
    U-->Close
