version: "3.9"

services:
  tileserv:
    image: pramsey/pg_tileserv:20210210
    environment:
      - DATABASE_URL=postgresql://map_dev_user:map_pwd@db/map_dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 7800:7800
    restart: unless-stopped

  db:
    image: kartoza/postgis:13-3.1
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/work
      - ./load-data-db.sh:/docker-entrypoint-initdb.d/load_data-db.sh
    environment:
      - POSTGRES_USER=map_dev_user
      - POSTGRES_PASS=map_pwd
      - POSTGRES_DB=map_dev
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -U map_dev_user -d map_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
