graph TD
    Dataset1["Dataset 1"]-->Score
    Dataset2["Dataset 2"]-->Score
    Census["Census TIGER Data"]-->CGTiger
    CGTiger["Create GeoJSON from Shapefile with osgeo/gdal"]-->TS3
    TS3("TIGER GeoJSON (S3)")-->CGJ
    Score["Create Score CSV"]-->CSV
    CSV("CSV (S3)")-->CGJ
    CGJ["Combine (ogr2ogr)+ Create GeoJSON"]-->GeoJSON
    GeoJSON("GeoJSON (S3)")-->Tip
    GeoJSON--"Access non-geo data"-->Client
    subgraph "Generate MVT"
        Tip[/Tippecanoe/]-->CreateMVT["Create and Send MVT"]
    end
    subgraph production
        CreateMVT-->Uncompressed("Uncompressed MVT (S3)")
    end
    subgraph development
        CreateMVT-->Compressed("MBTiles (S3)")-->TS[/Tileserver-GL/]
    end
    TS--"XYZ URL"-->Client
    Uncompressed--"XYZ URL"-->Client["Gatsby+OpenLayers"]
