Resources:

  ARecordDataHarvester:
    Type: AWS::Route53::RecordSetGroup
    Condition: ShouldOnlyCreateResourcesInSIT
    # DependsOn:
    #   - DataDistribution
    Properties:
      HostedZoneId: ${self:custom.environment.HOSTED_ZONE_ID_DOMAIN}
      RecordSets:
        - Name: ${self:custom.environment.HOSTED_ZONE_SUBDOMAIN}.${self:custom.environment.HOSTED_ZONE_DOMAIN}.
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2 # AWS global value https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
            # DNSName:
              # Fn::GetAtt: [ DataDistribution, DomainName ]

